/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Fuzzy string matcher. Finds approximate
 * matches within edit distance k, immune to
 * typos, OCR errors, and diacritics variants.
 *
 * Pattern names are handled in the JS wrapper
 * (not stored here).
 */
export declare class FuzzySearch {
  /**
   * Build a fuzzy matcher from the given
   * patterns and options.
   */
  constructor(patterns: Array<PatternEntry>, options?: Options | undefined | null)
  /** Number of patterns in the matcher. */
  get patternCount(): number
  /**
   * Returns `true` if any pattern matches
   * within its edit distance.
   */
  isMatch(haystack: string): boolean
  /**
   * Find all fuzzy matches. Returns a packed
   * `Uint32Array` of `[pattern, start, end,
   * distance]` quads. The JS wrapper unpacks
   * these into `FuzzyMatch` objects.
   */
  _findIterPacked(haystack: string): Uint32Array
  /**
   * Replace all fuzzy matches.
   * `replacements[i]` replaces pattern `i`.
   */
  replaceAll(haystack: string, replacements: Array<string>): string
}

/** A single fuzzy match (packed representation). */
export interface FuzzyMatch {
  /** Index into the patterns array. */
  pattern: number
  /** Start offset (UTF-16 code units). */
  start: number
  /** End offset (exclusive, UTF-16 code units). */
  end: number
  /** Actual edit distance of the match. */
  distance: number
}

/** Distance metric for fuzzy matching. */
export declare const enum Metric {
  /**
   * Standard Levenshtein: insertions, deletions,
   * substitutions.
   */
  Levenshtein = 'levenshtein',
  /**
   * Damerau-Levenshtein: insertions, deletions,
   * substitutions, and transpositions of
   * adjacent characters.
   */
  DamerauLevenshtein = 'damerau-levenshtein'
}

/** Options for constructing a `FuzzySearch`. */
export interface Options {
  /** Distance metric. Default: `"levenshtein"`. */
  metric?: Metric
  /**
   * Strip diacritics before matching (NFD
   * decompose + remove combining marks).
   * Default: `false`.
   */
  normalizeDiacritics?: boolean
  /**
   * Use Unicode word boundaries.
   * Default: `true`.
   */
  unicodeBoundaries?: boolean
  /** Only match whole words. Default: `true`. */
  wholeWords?: boolean
  /** Case-insensitive matching. Default: `false`. */
  caseInsensitive?: boolean
}

/** A pattern entry for fuzzy search. */
export interface PatternEntry {
  /** The pattern string to search for. */
  pattern: string
  /** Maximum edit distance (1-3). Default: 1. */
  distance?: number
  /** Optional name for the pattern. */
  name?: string
}
